[package]
name = "library"
version = "0.0.0"
edition = "2021"

[dependencies]
env_logger = "0.10"
failure = "0.1"
log = "0.4"
magpie = { path = "../magpie" }
serde = "1"

[lib]
name = "library"
path = "src/lib.rs"

[[bin]]
name = "magpie-library-init"
path = "src/init.rs"

[[bin]]
name = "magpie-library-sync"
path = "src/main.rs"